// <auto-generated />
namespace eksp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class workrole_change_fk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(workrole_change_fk));
        
        string IMigrationMetadata.Id
        {
            get { return "201701072227034_workrole_change_fk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
